spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rpd?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  security:
    oauth2:
      basic:
        enable: false
      client:
        registration:   
          google:   
            client-id: 787222402243-inil9burg0rtq015qdv0utnjt7k4s148.apps.googleusercontent.com
            client-secret: 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